services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: chatbot-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: chatbot_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7-alpine
    container_name: chatbot-redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: chatbot-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build: ./backend
    container_name: chatbot-backend
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_NAME=chatbot_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=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
      - GEMINI_API_KEY=AQ.Ab8RN6JyfBrZTS8O8PnGvOTH59Aqm0F3V98uUcs9RDzbbCmlFQ
      - DEEPSEEK_API_KEY=sk-6afcb9c9ea194924b7037362f7aaa30f
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api/v1
      - NEXT_PUBLIC_OPENAI_API_KEY=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
      - NEXT_PUBLIC_GEMINI_API_KEY=AQ.Ab8RN6JyfBrZTS8O8PnGvOTH59Aqm0F3V98uUcs9RDzbbCmlFQ
      - NEXT_PUBLIC_DEEPSEEK_API_KEY=sk-6afcb9c9ea194924b7037362f7aaa30f
    depends_on:
      - backend

volumes:
  pgdata: