import { ABTestExperiment } from "../types";

export const initialABExperiments: ABTestExperiment[] = [
  {
    id: "ab-1",
    name: "Enterprise Pitch: Rachel (Direct & Fast) vs Marcus (Empathetic Storytelling)",
    status: "running",
    baseAgentId: "agent-1",
    trafficSplitPercent: 50,
    variantA: {
      name: "Variant A: Direct ROI & Velocity",
      voiceName: "Rachel (US Professional)",
      provider: "ElevenLabs",
      promptPreview: "Directly qualify budget and monthly call volume within 60 seconds. Push for immediate video demo.",
      greeting: "Hi there! Rachel from Apex. We help call centers automate 60k+ minutes with sub-300ms voice AI. How many calls does your team handle daily?",
    },
    variantB: {
      name: "Variant B: Empathetic Pain-Point Discovery",
      voiceName: "Marcus (Calm & Empathetic)",
      provider: "Cartesia",
      promptPreview: "Listen to the customer's IVR pain points first. Build rapport before offering a technical consultation.",
      greeting: "Hello, this is Marcus with Apex Voice Systems. I understand managing high call volumes can be exhausting for support agents. What's been the biggest bottleneck for your team lately?",
    },
    metricsA: {
      callsCount: 0,
      answerRate: 0.0,
      conversionRate: 0.0,
      avgDurationSec: 0,
      sentimentScore: 0,
    },
    metricsB: {
      callsCount: 0,
      answerRate: 0.0,
      conversionRate: 0.0,
      avgDurationSec: 0,
      sentimentScore: 0,
    },
    confidenceScore: 0.0,
    winner: undefined,
    startDate: "2026-08-10T00:00:00Z",
  },
  {
    id: "ab-2",
    name: "Solar Outreach: Bella (High Energy) vs Asteria (Crisp & Technical)",
    status: "running",
    baseAgentId: "agent-3",
    trafficSplitPercent: 50,
    variantA: {
      name: "Variant A: High Energy Solar Savings",
      voiceName: "Bella (Engaging & Clear)",
      provider: "ElevenLabs",
      promptPreview: "Emphasize immediate 30% federal tax credit and SDG&E $350 rate hikes.",
      greeting: "Hey! Bella here with SunPeak Energy. California utility rates just jumped 22%—did you check your roof rebate qualification yet?",
    },
    variantB: {
      name: "Variant B: Engineering & NEM 3.0 Battery Pitch",
      voiceName: "Asteria (Crisp & Helpful)",
      provider: "Deepgram",
      promptPreview: "Provide exact kWh calculations and battery storage backup guarantees.",
      greeting: "Hello, Asteria with SunPeak Technical Audits. We are reviewing residential battery storage grid resilience in your zip code.",
    },
    metricsA: {
      callsCount: 0,
      answerRate: 0.0,
      conversionRate: 0.0,
      avgDurationSec: 0,
      sentimentScore: 0,
    },
    metricsB: {
      callsCount: 0,
      answerRate: 0.0,
      conversionRate: 0.0,
      avgDurationSec: 0,
      sentimentScore: 0,
    },
    confidenceScore: 0.0,
    winner: undefined,
    startDate: "2026-08-14T00:00:00Z",
  },
];
