import { Agent } from "../types";

export const initialAgents: Agent[] = [
  {
    id: "agent-solar-1",
    name: "Marcus (Solar Advisor)",
    description: "Specialized in commercial & residential solar qualification, financing options, and calendar booking.",
    avatar: "/avatars/marcus.png",
    color: "#3157D5",
    status: "active",
    voice: {
      provider: "ElevenLabs",
      voiceId: "v-marcus-turbo",
      voiceName: "Marcus (Conversational Professional)",
      gender: "male",
      accent: "American (West Coast)",
      speed: 1.0,
      pitch: 1.0,
      stability: 0.75,
      similarity: 0.85,
    },
    language: "English (US)",
    greeting: "Hello, this is Marcus with Apex Solar Solutions. How are you today?",
    systemPrompt: "You are Marcus, an empathetic and professional solar consultant. Your goal is to qualify homeowners and schedule consultation demos.",
    responseStyle: "conversational",
    interruptionSensitivity: 0.7,
    silenceTimeoutSeconds: 4,
    maxCallDurationMinutes: 15,
    knowledgeBaseIds: ["kb-solar-faq", "kb-pricing-2026"],
    tools: [
      { id: "tool-cal", name: "Google Calendar Booking", description: "Books meeting slots dynamically", enabled: true, type: "calendar" },
      { id: "tool-crm", name: "HubSpot Deal Push", description: "Pushes contact and qualification score", enabled: true, type: "crm" },
    ],
    transferRules: {
      enabled: true,
      destinationNumber: "+1 (800) 555-0199",
      triggerPhrase: "transfer to human specialist",
      department: "Senior Engineering",
    },
    callEndingRules: {
      goodbyePhrase: "Thank you for your time. Have a wonderful day!",
      hangupOnSilence: true,
      afterHoursBehavior: "voicemail",
    },
    metrics: {
      totalCalls: 0,
      avgDurationSeconds: 0,
      successRate: 0,
      sentimentScore: 0,
      connectedCalls: 0,
    },
    lastUpdated: "2026-06-17 14:00",
  },
  {
    id: "agent-sdr-2",
    name: "Rachel (Enterprise SDR)",
    description: "Inbound and outbound B2B pipeline development, discovery qualifications, and meeting confirmations.",
    avatar: "/avatars/rachel.png",
    color: "#6366F1",
    status: "active",
    voice: {
      provider: "Cartesia",
      voiceId: "v-rachel-sonic",
      voiceName: "Rachel (Executive & Clear)",
      gender: "female",
      accent: "American (Neutral)",
      speed: 1.05,
      pitch: 1.0,
      stability: 0.8,
      similarity: 0.9,
    },
    language: "English (US)",
    greeting: "Hi there, this is Rachel from Apex Enterprise. Reaching out regarding your AI telephony inquiry.",
    systemPrompt: "You are Rachel, a sharp and engaging enterprise sales representative.",
    responseStyle: "professional",
    interruptionSensitivity: 0.65,
    silenceTimeoutSeconds: 3,
    maxCallDurationMinutes: 20,
    knowledgeBaseIds: ["kb-enterprise-case-studies"],
    tools: [
      { id: "tool-email", name: "Send Demo Dossier", description: "Dispatches PDF overview to lead email", enabled: true, type: "sms" },
    ],
    transferRules: {
      enabled: true,
      destinationNumber: "+1 (800) 555-0188",
      triggerPhrase: "speak with account executive",
      department: "Enterprise Sales",
    },
    callEndingRules: {
      goodbyePhrase: "I'll send over the meeting brief now. Have a great day!",
      hangupOnSilence: true,
      afterHoursBehavior: "transfer",
    },
    metrics: {
      totalCalls: 0,
      avgDurationSeconds: 0,
      successRate: 0,
      sentimentScore: 0,
      connectedCalls: 0,
    },
    lastUpdated: "2026-06-17 12:30",
  },
  {
    id: "agent-support-3",
    name: "Elena (Customer Support & Billing)",
    description: "24/7 autonomous tier-1 customer care, invoice explanations, and order status lookups.",
    avatar: "/avatars/elena.png",
    color: "#0D9488",
    status: "paused",
    voice: {
      provider: "OpenAI",
      voiceId: "v-elena-empathy",
      voiceName: "Elena (Empathetic Support)",
      gender: "female",
      accent: "British (RP)",
      speed: 0.95,
      pitch: 1.0,
      stability: 0.9,
      similarity: 0.95,
    },
    language: "English (UK)",
    greeting: "Good day, thank you for calling Apex Customer Care. How may I assist you today?",
    systemPrompt: "You are Elena, a courteous and patient support representative.",
    responseStyle: "empathetic",
    interruptionSensitivity: 0.8,
    silenceTimeoutSeconds: 5,
    maxCallDurationMinutes: 30,
    knowledgeBaseIds: ["kb-billing-support-faq"],
    tools: [
      { id: "tool-lookup", name: "Order & Invoice DB Lookup", description: "Queries customer records by phone number", enabled: true, type: "crm" },
    ],
    transferRules: {
      enabled: true,
      destinationNumber: "+1 (800) 555-0111",
      triggerPhrase: "escalate to supervisor",
      department: "Tier 2 Support",
    },
    callEndingRules: {
      goodbyePhrase: "Thank you for contacting customer support. Take care!",
      hangupOnSilence: false,
      afterHoursBehavior: "voicemail",
    },
    metrics: {
      totalCalls: 0,
      avgDurationSeconds: 0,
      successRate: 0,
      sentimentScore: 0,
      connectedCalls: 0,
    },
    lastUpdated: "2026-06-17 09:15",
  },
];
