import { DashboardKPI, ActivityTimelineItem } from "../types";

export const initialKPIs: DashboardKPI[] = [
  {
    title: "Total Calls",
    value: "0",
    change: "0.0%",
    isPositive: true,
    period: "vs previous 30 days",
    icon: "PhoneCall",
    sparkline: [0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    title: "Inbound Volume",
    value: "0",
    change: "0.0%",
    isPositive: true,
    period: "0.0% of total traffic",
    icon: "PhoneIncoming",
    sparkline: [0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    title: "Outbound Volume",
    value: "0",
    change: "0.0%",
    isPositive: true,
    period: "0.0% of total traffic",
    icon: "PhoneOutgoing",
    sparkline: [0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    title: "Answer Rate",
    value: "0.0%",
    change: "0.0%",
    isPositive: true,
    period: "Industry avg 74.2%",
    icon: "CheckCircle2",
    sparkline: [0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    title: "Qualified Leads",
    value: "0",
    change: "0.0%",
    isPositive: true,
    period: "Score > 75 points",
    icon: "Award",
    sparkline: [0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    title: "Appointments Booked",
    value: "0",
    change: "0.0%",
    isPositive: true,
    period: "Auto-synced to calendar",
    icon: "Calendar",
    sparkline: [0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    title: "Avg Call Duration",
    value: "0m 00s",
    change: "0s",
    isPositive: true,
    period: "Optimal resolution speed",
    icon: "Clock",
    sparkline: [0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    title: "Active Campaigns",
    value: "0",
    change: "0 Running",
    isPositive: true,
    period: "0 Paused, 0 Draft",
    icon: "Megaphone",
    sparkline: [0, 0, 0, 0, 0, 0, 0, 0],
  },
  {
    title: "Credits Remaining",
    value: "$0.00",
    change: "~0 mins",
    isPositive: true,
    period: "Auto-recharge enabled",
    icon: "Coins",
    sparkline: [0, 0, 0, 0, 0, 0, 0, 0],
  },
];

export const callVolumeByHour = [
  { hour: "08:00", inbound: 0, outbound: 0, qualified: 0 },
  { hour: "09:00", inbound: 0, outbound: 0, qualified: 0 },
  { hour: "10:00", inbound: 0, outbound: 0, qualified: 0 },
  { hour: "11:00", inbound: 0, outbound: 0, qualified: 0 },
  { hour: "12:00", inbound: 0, outbound: 0, qualified: 0 },
  { hour: "13:00", inbound: 0, outbound: 0, qualified: 0 },
  { hour: "14:00", inbound: 0, outbound: 0, qualified: 0 },
  { hour: "15:00", inbound: 0, outbound: 0, qualified: 0 },
  { hour: "16:00", inbound: 0, outbound: 0, qualified: 0 },
  { hour: "17:00", inbound: 0, outbound: 0, qualified: 0 },
  { hour: "18:00", inbound: 0, outbound: 0, qualified: 0 },
];

export const callOutcomesDistribution = [
  { name: "Qualified / Booked", value: 0, color: "#3157D5" },
  { name: "General Inquiries", value: 0, color: "#5C82FF" },
  { name: "Transferred to Human", value: 0, color: "#1E40AF" },
  { name: "Voicemail / No Answer", value: 0, color: "#93C5FD" },
  { name: "Unqualified / DNC", value: 0, color: "#0F172A" },
];

export const latencyPercentiles = [
  { name: "STT (Deepgram Nova-2)", p50: 0, p90: 0, p99: 0 },
  { name: "LLM First Token (Claude 3.5)", p50: 0, p90: 0, p99: 0 },
  { name: "TTS Audio Stream (ElevenLabs)", p50: 0, p90: 0, p99: 0 },
  { name: "End-to-End Speech Turn", p50: 0, p90: 0, p99: 0 },
];

export const initialTimelineEvents: ActivityTimelineItem[] = [
  {
    id: "tl-1",
    time: "2 mins ago",
    title: "Demo Booked by Apex Qualifier Pro",
    description: "Jonathan Vance (ScaleOps Inc.) confirmed 30-min architecture review for Thursday 2:00 PM PST.",
    type: "appointment",
    badgeText: "Booked",
    badgeVariant: "success",
  },
  {
    id: "tl-2",
    time: "8 mins ago",
    title: "High-Volume Call Spike Detected",
    description: "California Clean Energy Rebate Outreach reached 38 concurrent channels with 0 latency drop.",
    type: "campaign",
    badgeText: "Concurr: 38",
    badgeVariant: "info",
  },
  {
    id: "tl-3",
    time: "18 mins ago",
    title: "Knowledge Base Synchronized",
    description: "Successfully indexed 'California NEM 3.0 & Solar Tax Incentives 2026' (96 vector embeddings).",
    type: "kb",
    badgeText: "Indexed",
    badgeVariant: "success",
  },
  {
    id: "tl-4",
    time: "35 mins ago",
    title: "Clinical Triage Routing",
    description: "MedCare Assistant successfully transferred patient Marcus Sterling to nurse hotline (+1 888-432-8472).",
    type: "call",
    badgeText: "Transferred",
    badgeVariant: "warning",
  },
  {
    id: "tl-5",
    time: "1 hour ago",
    title: "Agent Settings Updated",
    description: "Updated interruption sensitivity to 0.75 and enabled crm_lead_enrich tool for Apex Qualifier Pro.",
    type: "agent",
    badgeText: "Config",
    badgeVariant: "neutral",
  },
  {
    id: "tl-6",
    time: "2 hours ago",
    title: "Credits Auto-Recharged",
    description: "Added $500.00 credits via corporate Visa ending in 4289. Invoice #INV-2026-8891 generated.",
    type: "billing",
    badgeText: "+$500.00",
    badgeVariant: "success",
  },
  {
    id: "tl-7",
    time: "3 hours ago",
    title: "Campaign Schedule Initiated",
    description: "MedCare Preventive Wellness Recall launched morning calling batch (450 target contacts).",
    type: "campaign",
    badgeText: "Batch Run",
    badgeVariant: "info",
  },
  {
    id: "tl-8",
    time: "4 hours ago",
    title: "New SIP Trunk Connected",
    description: "US-West Telnyx SIP Endpoint passed health check (18ms ping latency, TLS 1.3 enabled).",
    type: "call",
    badgeText: "SIP Online",
    badgeVariant: "success",
  },
];
