import { Appointment } from "../types";

export const initialAppointments: Appointment[] = [
  {
    id: "apt-live-101",
    contactId: "lead-101",
    contactName: "Jonathan Vance",
    contactPhone: "+1 (415) 890-2341",
    contactEmail: "jonathan.vance@solarenergy.org",
    agentId: "agent-solar-1",
    agentName: "Marcus (Solar Advisor)",
    title: "Commercial Solar Consultation",
    scheduledTime: "Fri Oct 02, 10:00 AM PDT",
    scheduledAt: "2026-10-02T17:00:00Z",
    durationMinutes: 30,
    status: "confirmed",
    calendarType: "google",
    meetingLink: "https://meet.google.com/new",
    notes: "Homeowner qualified via AI voice inbound call. Interested in 12kW system with dual battery backup.",
    createdAt: "2026-10-01T14:30:00Z",
  },
  {
    id: "apt-live-102",
    contactId: "lead-102",
    contactName: "Sarah Lin",
    contactPhone: "+1 (310) 456-7890",
    contactEmail: "sarah.lin@apexvoice.io",
    agentId: "agent-solar-1",
    agentName: "Marcus (Solar Advisor)",
    title: "Battery Storage & Solar Survey",
    scheduledTime: "Mon Oct 05, 2:30 PM PDT",
    scheduledAt: "2026-10-05T21:30:00Z",
    durationMinutes: 45,
    status: "confirmed",
    calendarType: "google",
    meetingLink: "https://meet.google.com/new",
    notes: "Follow-up solar demo. Roof structural analysis and ROI forecast to be presented.",
    createdAt: "2026-10-02T09:15:00Z",
  },
  {
    id: "apt-live-103",
    contactId: "lead-103",
    contactName: "David Miller",
    contactPhone: "+1 (212) 345-6789",
    contactEmail: "david.m@cleanpower.net",
    agentId: "agent-solar-1",
    agentName: "Marcus (Solar Advisor)",
    title: "Residential Solar Assessment",
    scheduledTime: "Thu Oct 08, 11:00 AM EDT",
    scheduledAt: "2026-10-08T15:00:00Z",
    durationMinutes: 30,
    status: "completed",
    calendarType: "google",
    meetingLink: "https://meet.google.com/new",
    notes: "Initial consultation completed. Financing options and federal tax credit breakdown sent.",
    createdAt: "2026-10-01T11:00:00Z",
  },
  {
    id: "apt-live-104",
    contactId: "lead-104",
    contactName: "Elena Rostova",
    contactPhone: "+1 (415) 639-0491",
    contactEmail: "elena.r@bayareahomes.com",
    agentId: "agent-solar-1",
    agentName: "Marcus (Solar Advisor)",
    title: "EV Charging & Solar Integration",
    scheduledTime: "Wed Oct 14, 1:00 PM PDT",
    scheduledAt: "2026-10-14T20:00:00Z",
    durationMinutes: 30,
    status: "scheduled",
    calendarType: "google",
    meetingLink: "https://meet.google.com/new",
    notes: "Wants to combine Tesla Level 2 charger installation with 8kW rooftop panels.",
    createdAt: "2026-10-02T16:20:00Z",
  },
];
