import { Contact } from "../types";

export const initialContacts: Contact[] = [
  {
    id: "cont-1",
    name: "Dr. Jonathan Vance",
    phone: "+1 (555) 432-8899",
    email: "jonathan.vance@apexhealth.org",
    company: "Apex Healthcare Systems",
    leadScore: 95,
    status: "qualified",
    campaignName: "Executive Medical Triage",
    lastCallOutcome: "Appointment Booked",
    notes: "[Call Outcome: Appointment Booked] Handled by Elena (Customer Care). Caller requested solutions consultation. Verified contact details and locked Google Calendar slot. High purchasing intent.",
    tags: ["VIP", "High Intent", "Medical"],
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "cont-2",
    name: "Sarah Jenkins",
    phone: "+1 (415) 890-2341",
    email: "sarah.jenkins@lumina-cloud.io",
    company: "Lumina Cloud Architecture",
    leadScore: 88,
    status: "qualified",
    campaignName: "Cloud Solutions Inbound",
    lastCallOutcome: "Knowledge Inquiry / Price Check",
    notes: "[Call Outcome: Knowledge Inquiry / Price Check] Caller inquired about SOC2 Type II compliance and Tier 3 volume discounts. AI provided SOC2 & Tier-1 pricing dossier. Caller showed interest.",
    tags: ["Enterprise", "SOC2 Check"],
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: "cont-3",
    name: "Michael Scott",
    phone: "+1 (555) 902-1133",
    email: "michael.scott@dunder.com",
    company: "Dunder Mifflin Paper Co",
    leadScore: 60,
    status: "contacted",
    campaignName: "Outbound Sales Sprint",
    lastCallOutcome: "No Answer / Missed",
    notes: "[Call Outcome: No Answer / Missed] Outbound call attempted by Marcus Vance. No pickup detected after 25s ring. Scheduled for automated Smart-AMD retry.",
    tags: ["Outbound", "Retry Scheduled"],
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: "cont-4",
    name: "Elena Rostova",
    phone: "+1 (312) 555-7821",
    email: "elena.rostova@fintech-edge.com",
    company: "FinTech Edge Capital",
    leadScore: 92,
    status: "qualified",
    campaignName: "Executive Wealth Inbound",
    lastCallOutcome: "Demo Scheduled",
    notes: "High net-worth asset management inquiry. Interested in low-latency voice trading tools.",
    tags: ["Finance", "High Value"],
    createdAt: new Date(Date.now() - 36 * 3600000).toISOString(),
  },
  {
    id: "cont-5",
    name: "David Kim",
    phone: "+1 (206) 555-3419",
    email: "david.kim@nexus-robotics.ai",
    company: "Nexus Robotics AI",
    leadScore: 84,
    status: "appointment_set",
    campaignName: "Tech Founders Outbound",
    lastCallOutcome: "Discovery Call Locked",
    notes: "Requires custom Twilio SIP trunk integration with real-time whisper coaching.",
    tags: ["AI", "Tech"],
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
  {
    id: "cont-6",
    name: "Amanda Chen",
    phone: "+1 (617) 555-8912",
    email: "achen@biotech-innovate.org",
    company: "BioTech Innovate",
    leadScore: 78,
    status: "contacted",
    campaignName: "Healthcare Compliance",
    lastCallOutcome: "Information Sent",
    notes: "Requested HIPAA compliance architecture sheet and signed BAA terms.",
    tags: ["Healthcare", "HIPAA"],
    createdAt: new Date(Date.now() - 60 * 3600000).toISOString(),
  },
  {
    id: "cont-7",
    name: "Robert Morales",
    phone: "+1 (713) 555-6623",
    email: "robert.m@lonestar-logistics.com",
    company: "Lone Star Logistics",
    leadScore: 71,
    status: "new",
    campaignName: "Fleet Dispatch Inbound",
    lastCallOutcome: "Not Called Yet",
    notes: "Fleet dispatch triage. Inquiring about automated driver check-ins.",
    tags: ["Logistics", "Inbound"],
    createdAt: new Date(Date.now() - 72 * 3600000).toISOString(),
  },
  {
    id: "cont-8",
    name: "Jessica Taylor",
    phone: "+1 (404) 555-9011",
    email: "jtaylor@summit-retail.com",
    company: "Summit Retail Partners",
    leadScore: 89,
    status: "qualified",
    campaignName: "Omnichannel Support",
    lastCallOutcome: "Pricing Proposal Requested",
    notes: "Multi-location retail chain looking to replace Tier-1 support desk.",
    tags: ["Retail", "High Intent"],
    createdAt: new Date(Date.now() - 84 * 3600000).toISOString(),
  },
  {
    id: "cont-9",
    name: "Thomas Wright",
    phone: "+1 (303) 555-4509",
    email: "twright@milehigh-solar.com",
    company: "Mile High Solar",
    leadScore: 65,
    status: "contacted",
    campaignName: "Solar Lead Qualification",
    lastCallOutcome: "Follow-up Next Week",
    notes: "Needs 20kW residential solar quote. Homeowner verified.",
    tags: ["Solar", "Residential"],
    createdAt: new Date(Date.now() - 96 * 3600000).toISOString(),
  },
  {
    id: "cont-10",
    name: "Olivia Martinez",
    phone: "+1 (305) 555-1288",
    email: "omartinez@coastal-realty.net",
    company: "Coastal Realty Group",
    leadScore: 94,
    status: "appointment_set",
    campaignName: "Luxury Property Inbound",
    lastCallOutcome: "Property Tour Booked",
    notes: "Buyer consultation scheduled for waterfront luxury property.",
    tags: ["Real Estate", "VIP"],
    createdAt: new Date(Date.now() - 110 * 3600000).toISOString(),
  },
];
