import { ConversationFunnelStep } from "../types";

export const initialFunnelSteps: ConversationFunnelStep[] = [
  {
    id: "step-1",
    stepNumber: 1,
    stepName: "Greeting & Brand Introduction",
    nodeType: "greeting",
    visitorsCount: 0,
    completedCount: 0,
    dropOffRatePercent: 0.0,
    dropOffReason: "No call traffic recorded yet.",
    aiOptimizationTip: "Keep greeting under 12 words. Introduce agent within the first 1.5 seconds.",
  },
  {
    id: "step-2",
    stepNumber: 2,
    stepName: "Core Intent / Problem Discovery",
    nodeType: "question",
    visitorsCount: 0,
    completedCount: 0,
    dropOffRatePercent: 0.0,
    dropOffReason: "No call traffic recorded yet.",
    aiOptimizationTip: "Use open-ended empathy phrasing: 'What has been the biggest challenge for your queue?'",
  },
  {
    id: "step-3",
    stepNumber: 3,
    stepName: "Call Volume & Tech Stack Qualification",
    nodeType: "collect_info",
    visitorsCount: 0,
    completedCount: 0,
    dropOffRatePercent: 0.0,
    dropOffReason: "No call traffic recorded yet.",
    aiOptimizationTip: "State starting pricing ($0.08/min) BEFORE asking for monthly minutes.",
  },
  {
    id: "step-4",
    stepNumber: 4,
    stepName: "Knowledge Base & Security SLA Match",
    nodeType: "knowledge_lookup",
    visitorsCount: 0,
    completedCount: 0,
    dropOffRatePercent: 0.0,
    dropOffReason: "No call traffic recorded yet.",
    aiOptimizationTip: "Pre-fetch compliance certificate highlights automatically into first response.",
  },
  {
    id: "step-5",
    stepNumber: 5,
    stepName: "Calendar Demo Proposal & Slot Reservation",
    nodeType: "appointment",
    visitorsCount: 0,
    completedCount: 0,
    dropOffRatePercent: 0.0,
    dropOffReason: "No call traffic recorded yet.",
    aiOptimizationTip: "Offer flexible morning vs afternoon options rather than a single rigid time slot.",
  },
  {
    id: "step-6",
    stepNumber: 6,
    stepName: "SMS Confirmation & Graceful Closing",
    nodeType: "end_call",
    visitorsCount: 0,
    completedCount: 0,
    dropOffRatePercent: 0.0,
    dropOffReason: "No call traffic recorded yet.",
    aiOptimizationTip: "Dispatch SMS confirmation payload asynchronously before goodbye phrase.",
  },
];
