import { IncomingConnection } from "../types";

export const initialIncomingConnections: IncomingConnection[] = [
  {
    id: "conn-1",
    name: "US-East Twilio BYOC Trunk",
    provider: "Twilio BYOC",
    sipUri: "sip:apex-voice-inbound.pstn.twilio.com",
    status: "connected",
    activeChannels: 0,
    maxChannels: 100,
    routedAgentId: "agent-1",
    routedAgentName: "Apex Qualifier Pro",
    latencyMs: 0,
    lastPing: "Just now",
  },
  {
    id: "conn-2",
    name: "Telnyx California Elastic SIP",
    provider: "Telnyx SIP",
    sipUri: "sip:telnyx-west.apexai.global:5060",
    status: "connected",
    activeChannels: 0,
    maxChannels: 250,
    routedAgentId: "agent-3",
    routedAgentName: "SolarLead Velocity",
    latencyMs: 0,
    lastPing: "Just now",
  },
  {
    id: "conn-3",
    name: "WebRTC In-App Voice Widget",
    provider: "WebRTC Endpoint",
    sipUri: "wss://webrtc-edge.apexai.global/live",
    status: "connected",
    activeChannels: 0,
    maxChannels: 500,
    routedAgentId: "agent-4",
    routedAgentName: "PrimeDesk Support & Returns",
    latencyMs: 0,
    lastPing: "Just now",
  },
  {
    id: "conn-4",
    name: "Vonage UK Carrier Gateway",
    provider: "Vonage SIP",
    sipUri: "sip:lon-gateway.vonage.com",
    status: "connected",
    activeChannels: 0,
    maxChannels: 50,
    routedAgentId: "agent-5",
    routedAgentName: "Estates Concierge AI",
    latencyMs: 0,
    lastPing: "Just now",
  },
];
