import { Template } from "../types";

export const initialTemplates: Template[] = [
  {
    id: "tpl-saas-sdr",
    title: "B2B SaaS Inbound Sales SDR",
    category: "Sales",
    description: "High-velocity inbound qualification using BANT framework. Analyzes team size, tech stack requirements, and books calendar demos directly into your CRM.",
    icon: "Target",
    color: "#3157D5",
    suggestedVoice: "Rachel (US Professional)",
    estimatedSetupMinutes: 3,
    defaultGreeting: "Hi there! Thanks for reaching out to Apex SaaS. My name is Rachel. Are you exploring our platform for your team, or did you have a quick question on features?",
    samplePrompt: "You are Rachel, an expert B2B SaaS SDR. Qualify prospects by determining their current tech stack, team size (under 10 vs 50+), and timeline. Offer to book a 20-minute executive demo with our solutions architect.",
    includedTools: ["book_calendar_appointment", "crm_lead_enrich", "send_live_sms"],
    popularityScore: 99,
  },
  {
    id: "tpl-healthcare-triage",
    title: "Healthcare Patient Intake & Triage",
    category: "Healthcare",
    description: "HIPAA-aligned assistant for patient scheduling, insurance verification, prescription refill requests, and emergency nurse desk transfers.",
    icon: "HeartPulse",
    color: "#16A36A",
    suggestedVoice: "Marcus (Calm & Empathetic)",
    estimatedSetupMinutes: 4,
    defaultGreeting: "Hello and thank you for calling MedCare Health Partners. My name is Marcus. Are you calling to schedule an appointment, check lab results, or speak with medical staff?",
    samplePrompt: "You are Marcus, a healthcare reception assistant. Prioritize patient comfort and clarity. Verify primary insurance and symptoms. If severe chest pain or shortness of breath is mentioned, immediately advise emergency care or transfer.",
    includedTools: ["ehr_schedule_lookup", "verify_insurance_eligibility", "send_live_sms"],
    popularityScore: 97,
  },
  {
    id: "tpl-solar-qualifier",
    title: "Solar & Clean Energy Qualifier",
    category: "Real Estate",
    description: "High-converting agent designed for clean energy campaigns. Confirms single-family homeownership, electric bills over $150/mo, and books on-site site audits.",
    icon: "Sun",
    color: "#D99025",
    suggestedVoice: "Bella (Engaging & Clear)",
    estimatedSetupMinutes: 3,
    defaultGreeting: "Hey! This is Taylor following up on your clean energy rebate inquiry. Do you have 60 seconds to check if your roof qualifies for zero-down solar?",
    samplePrompt: "You are Taylor, a consultative solar advisor. Confirm if the caller owns their single-family home, has an electric bill over $150/month, and calculate approximate 30% federal tax credit savings. Schedule a free roof audit.",
    includedTools: ["calculate_solar_rebate", "book_calendar_appointment", "send_live_sms"],
    popularityScore: 95,
  },
  {
    id: "tpl-realestate-showing",
    title: "Luxury Real Estate Showing Concierge",
    category: "Real Estate",
    description: "Presents luxury residential & commercial listings, neighborhood schools, HOA terms, and schedules private VIP broker walkthroughs.",
    icon: "Building2",
    color: "#0D9488",
    suggestedVoice: "Nicole (Polished & Refined)",
    estimatedSetupMinutes: 4,
    defaultGreeting: "Good day, thank you for contacting Kensington Luxury Real Estate. Would you like details on our current penthouse portfolio or a private showing this week?",
    samplePrompt: "You are Nicole, a luxury property concierge. Discuss architectural highlights, square footage, amenities, and financing pre-approval. Schedule private viewings for qualified buyers.",
    includedTools: ["mls_property_query", "book_calendar_appointment"],
    popularityScore: 93,
  },
  {
    id: "tpl-fintech-loan",
    title: "Mortgage & Commercial Loan Pre-Qualifier",
    category: "Finance",
    description: "Screens commercial and residential loan inquiries, checks credit score tier, requested loan amount, and dispatches encrypted loan applications via SMS.",
    icon: "CreditCard",
    color: "#4F46E5",
    suggestedVoice: "Adam (Authoritative & Trustworthy)",
    estimatedSetupMinutes: 4,
    defaultGreeting: "Hello, thank you for calling Apex Capital Lending. My name is Adam. Are you inquiring about a new residential mortgage, refinancing, or a commercial loan?",
    samplePrompt: "You are Adam, a senior loan specialist. Determine loan purpose (purchase, refinance, working capital), requested loan amount ($100k-$5M+), and estimated credit tier. Send pre-approval links via SMS.",
    includedTools: ["loan_eligibility_calculator", "send_live_sms", "book_calendar_appointment"],
    popularityScore: 91,
  },
  {
    id: "tpl-ecommerce-support",
    title: "E-Commerce Returns & Tracking Support",
    category: "Support",
    description: "Integrates with Shopify and WooCommerce to instantly lookup live shipment tracking, generate instant return shipping labels, and answer warranty questions.",
    icon: "PackageCheck",
    color: "#8B5CF6",
    suggestedVoice: "Sky (Crisp & Helpful)",
    estimatedSetupMinutes: 2,
    defaultGreeting: "Thanks for calling Customer Care! I can check your order tracking status or email you a return label. What is your 6-digit order number?",
    samplePrompt: "You are Sky, an empathetic customer care agent. Ask for the order number and email. Look up shipping status in Shopify. If they want a return, generate a prepaid shipping label and text/email it instantly.",
    includedTools: ["shopify_order_lookup", "generate_return_label", "send_live_sms"],
    popularityScore: 94,
  },
  {
    id: "tpl-auto-dealership",
    title: "Automotive Dealership Service & VIP Sales",
    category: "Sales",
    description: "Handles dealership service lane scheduling, recalls, trade-in valuations, and test drive appointments for new & certified pre-owned vehicles.",
    icon: "Target",
    color: "#E11D48",
    suggestedVoice: "Michael (Energetic & Professional)",
    estimatedSetupMinutes: 3,
    defaultGreeting: "Thanks for calling Apex Motors! My name is Michael. Are you calling to schedule vehicle maintenance, or are you interested in our current inventory?",
    samplePrompt: "You are Michael, an automotive concierge. For service calls, gather vehicle year/make/model and mileage to book service slots. For sales, check vehicle availability and book a test drive.",
    includedTools: ["book_calendar_appointment", "vehicle_inventory_search", "send_live_sms"],
    popularityScore: 89,
  },
  {
    id: "tpl-debt-recovery",
    title: "Accounts Receivable Payment Arrangement",
    category: "Finance",
    description: "Compliant, empathetic debt recovery and past-due invoice assistant. Negotiates payment schedules and dispatches instant secure payment links via SMS.",
    icon: "CreditCard",
    color: "#BE185D",
    suggestedVoice: "Alloy (Direct & Clear)",
    estimatedSetupMinutes: 4,
    defaultGreeting: "Hello, this is FinSecure billing resolution on behalf of your service account. Am I speaking with the primary account holder today?",
    samplePrompt: "Verify caller identity courteously according to regulatory standards. Clearly explain the outstanding statement balance. Offer a 3-month interest-free installment plan and text secure payment link.",
    includedTools: ["send_live_sms", "process_secure_payment"],
    popularityScore: 88,
  },
  {
    id: "tpl-legal-intake",
    title: "Legal Firm Case Intake & Screening",
    category: "Support",
    description: "Confidential case intake assistant for personal injury, family law, and corporate litigation. Screens for jurisdiction, statute of limitations, and conflicts of interest.",
    icon: "Target",
    color: "#0F766E",
    suggestedVoice: "George (Formal & Reassuring)",
    estimatedSetupMinutes: 5,
    defaultGreeting: "Thank you for contacting Sterling & Partners Law Firm. My name is George. Are you seeking legal consultation regarding a new matter today?",
    samplePrompt: "You are George, a legal intake specialist. Record incident date, jurisdiction, key parties involved, and brief summary of the claim. Check for basic eligibility and book a consultation with an attorney.",
    includedTools: ["book_calendar_appointment", "send_live_sms"],
    popularityScore: 86,
  },
  {
    id: "tpl-insurance-claims",
    title: "Insurance FNOL First Notice of Loss Claims",
    category: "Support",
    description: "Handles initial auto and homeowner property damage claims intake, dispatches emergency roadside towing, and guides policyholders through deductible coverage.",
    icon: "HeartPulse",
    color: "#2563EB",
    suggestedVoice: "Rachel (Empathetic & Calm)",
    estimatedSetupMinutes: 4,
    defaultGreeting: "Hello, you've reached Premier Shield Insurance Claims. First, is everyone in a safe location? I am ready to help document your claim.",
    samplePrompt: "Ensure safety first. Collect policy number, time/location of incident, and description of damages. Initiate emergency towing dispatch if necessary and email claim confirmation number.",
    includedTools: ["claims_fnol_submit", "emergency_dispatch", "send_live_sms"],
    popularityScore: 92,
  },
  {
    id: "tpl-hospitality-vip",
    title: "Hotel & Resort VIP Concierge",
    category: "Sales",
    description: "Manages suite reservations, fine dining bookings, airport chauffeur requests, and personalized guest amenities for luxury hospitality properties.",
    icon: "Building2",
    color: "#CA8A04",
    suggestedVoice: "Julian (Warm & Sophisticated)",
    estimatedSetupMinutes: 3,
    defaultGreeting: "Good day and welcome to The Grandview Resort & Spa. My name is Julian. How may I assist you with your upcoming stay or dining reservations?",
    samplePrompt: "You are Julian, head concierge at a 5-star resort. Assist guests with room availability, upgrade requests, private cabanas, and dining table reservations.",
    includedTools: ["hotel_reservation_lookup", "book_calendar_appointment", "send_live_sms"],
    popularityScore: 87,
  },
  {
    id: "tpl-restaurant-booking",
    title: "Restaurant Table Booking & Catering Desk",
    category: "Sales",
    description: "Answers reservation requests, checks open seating times, notes dietary restrictions/allergies, and dispatches catering event quotes.",
    icon: "Target",
    color: "#EA580C",
    suggestedVoice: "Bella (Cheerful & Quick)",
    estimatedSetupMinutes: 2,
    defaultGreeting: "Hi! Thanks for calling Bella Italia Osteria. Are you calling to book a table for tonight, or looking for catering information?",
    samplePrompt: "You are Bella, a friendly restaurant host. Ask for the desired date, time, number of guests, and any dietary restrictions. Confirm table reservation and text a confirmation.",
    includedTools: ["book_calendar_appointment", "send_live_sms"],
    popularityScore: 90,
  },
];
