export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
  dir: "ltr" | "rtl";
}

export const BASIC_LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English", nativeName: "English (US)", flag: "🇺🇸", dir: "ltr" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪", dir: "ltr" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸", dir: "ltr" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷", dir: "ltr" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹", dir: "ltr" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇧🇷", dir: "ltr" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺", dir: "ltr" },
  { code: "zh", name: "Chinese", nativeName: "中文 (简体)", flag: "🇨🇳", dir: "ltr" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵", dir: "ltr" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦", dir: "rtl" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳", dir: "ltr" },
  { code: "ur", name: "Urdu", nativeName: "اردو", flag: "🇵🇰", dir: "rtl" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷", dir: "ltr" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱", dir: "ltr" },
  { code: "pl", name: "Polish", nativeName: "Polski", flag: "🇵🇱", dir: "ltr" },
  { code: "sv", name: "Swedish", nativeName: "Svenska", flag: "🇸🇪", dir: "ltr" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", flag: "🇮🇩", dir: "ltr" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", flag: "🇻🇳", dir: "ltr" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷", dir: "ltr" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇧🇩", dir: "ltr" },
];

export const LANGUAGE_STORAGE_KEY = "apex_preferred_language";

export function getStoredLanguage(): string {
  if (typeof window === "undefined") return "en";
  try {
    return localStorage.getItem(LANGUAGE_STORAGE_KEY) || "en";
  } catch {
    return "en";
  }
}

export function setStoredLanguage(code: string): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, code);
    const lang = BASIC_LANGUAGES.find((l) => l.code === code);
    if (lang && document.documentElement) {
      document.documentElement.setAttribute("lang", code);
      document.documentElement.setAttribute("dir", lang.dir || "ltr");
    }
    window.dispatchEvent(new CustomEvent("apex-language-change", { detail: code }));
  } catch (e) {
    console.error("Failed to save preferred language", e);
  }
}

// Master Platform Translations Dictionary across 20 Languages
export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    overview: "Overview",
    voice_operations: "Voice Operations",
    live_calls: "Live Calls",
    live_supervisor: "Live Supervisor",
    voice_agents: "AI Voice Agents",
    flow_builder: "Visual Flow Builder",
    campaigns: "Outbound Campaigns",
    data_context: "Data & Context",
    knowledge_base: "Knowledge Base",
    contacts_leads: "Contacts & Leads",
    contacts_database: "Contacts & Lead Database",
    contacts_subtitle: "Unified ledger of inbound callers, outbound prospects, lead scores, and call histories.",
    calendar_bookings: "Calendar & Bookings",
    appointments: "Appointments",
    appointments_subtitle: "Manage and view scheduled appointments from AI calls",
    tools_integrations: "Tools & Integrations",
    tools: "Tools",
    google_sheets: "Google Sheets",
    phone_numbers: "Phone Numbers",
    sip_connections: "SIP Connections",
    smart_amd: "Smart AMD 2.0",
    intelligence_logs: "Intelligence & Logs",
    funnels: "Conversation Funnels",
    ab_testing: "A/B Testing Lab",
    call_history: "Call History",
    analytics: "Analytics Suite",
    workspace: "Workspace",
    templates: "Templates",
    credits_billing: "Credits & Billing",
    settings: "Settings",
    voice_recorder: "Voice Recorder & Audio Vault",
    voice_recorder_subtitle: "Listen, manage, reorder, search, and filter all historical call audio recordings, voice prompts, and AI waveforms.",
    voice_credits: "Voice Credits",
    add_funds: "Add Funds",
    my_dashboard: "My Dashboard",
    welcome_back: "Welcome back Alex DeVries • Enterprise Operations Active",
    enterprise_voice_operations: "Enterprise Voice Operations",
    today: "Today",
    export_csv: "Export CSV",
    add_lead: "Add Lead",
    new_booking: "New Booking",
    create_new_agent: "Create New Agent",
    save_settings: "Save Settings",
    save_changes: "Save Changes",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    download: "Download",
    sync: "Sync",
    sync_agent_stream: "Sync Agent Stream",
    record_voice_prompt: "Record Voice Prompt",
    connect_google_calendar: "Connect Google Calendar",
    google_calendar_connected: "Google Calendar Connected",
    search_leads_placeholder: "Search leads by name, email, phone, company...",
    search_placeholder: "Search Apex Voice AI (Agents, Calls, Leads)...",
    tab_all: "All",
    tab_new: "New",
    tab_qualified: "Qualified",
    tab_appointment_set: "Appointment Set",
    tab_contacted: "Contacted",
    tab_do_not_call: "Do Not Call",
    col_contact: "CONTACT",
    col_phone_email: "PHONE & EMAIL",
    col_lead_score: "LEAD SCORE",
    col_status: "STATUS",
    col_campaign: "CAMPAIGN",
    col_last_call_outcome: "LAST CALL OUTCOME",
    col_actions: "ACTIONS",
    no_contacts_recorded: "No contacts or leads recorded in database yet.",
    super_admin: "Super Admin",
    mission_control: "Mission Control",
    platform_control: "Platform Control",
    tenant_organizations: "Tenant Organizations",
    team_super_admins: "Team & Super Admins",
    team: "Team",
    global_calls_inspector: "Global Calls Inspector",
    infrastructure_ai: "Infrastructure & AI",
    telephony_sip_trunks: "Telephony & SIP Trunks",
    voice_ai_llm_engines: "Voice AI & LLM Engines",
    email_sms_gateways: "Email & SMS Gateways",
    external_servers: "External Servers",
    plans_billing_quotas: "Plans & Billing Quotas",
    security_dnc_waf: "Security, DNC & WAF",
    audit_logs_compliance: "Audit Logs & Compliance",
    global_announcements: "Global Announcements",
    analytics_revenue: "Analytics & Revenue",
  },
  de: {
    overview: "Übersicht",
    voice_operations: "Sprachbetrieb",
    live_calls: "Live-Anrufe",
    live_supervisor: "Live-Supervisor",
    voice_agents: "Sprach-Agenten",
    flow_builder: "Flow-Builder",
    campaigns: "Kampagnen",
    data_context: "Daten & Kontext",
    knowledge_base: "Wissensdatenbank",
    contacts_leads: "Kontakte & Leads",
    contacts_database: "Kontakte & Lead-Datenbank",
    contacts_subtitle: "Zentrales Verzeichnis aller eingehenden Anrufer, Interessenten, Lead-Bewertungen und Anrufverläufe.",
    calendar_bookings: "Kalender & Buchungen",
    appointments: "Termine & Buchungen",
    appointments_subtitle: "Verwalten und Anzeigen aller durch KI-Anrufe vereinbarten Termine.",
    tools_integrations: "Werkzeuge & Integrationen",
    tools: "Werkzeuge",
    google_sheets: "Google Tabellen Sync",
    phone_numbers: "Telefonnummern",
    sip_connections: "SIP-Verbindungen",
    smart_amd: "Smart AMD 2.0 Anrufbeantworter-Erkennung",
    intelligence_logs: "Intelligenz & Protokolle",
    funnels: "Konversationstrichter",
    ab_testing: "A/B-Testlabor",
    call_history: "Anrufverlauf",
    analytics: "Analytik-Suite",
    workspace: "Arbeitsbereich",
    templates: "Vorlagen",
    credits_billing: "Guthaben & Abrechnung",
    settings: "Einstellungen",
    voice_recorder: "Sprachrekorder & Audio-Tresor",
    voice_recorder_subtitle: "Anhören, Verwalten, Neuordnen, Suchen und Filtern aller historischen Anrufaufzeichnungen und Sprachansagen.",
    voice_credits: "Sprachguthaben",
    add_funds: "Guthaben aufladen",
    my_dashboard: "Mein Dashboard",
    welcome_back: "Willkommen zurück Alex DeVries • Unternehmensbetrieb Aktiv",
    enterprise_voice_operations: "Unternehmens-Sprachbetrieb",
    today: "Heute",
    export_csv: "CSV exportieren",
    add_lead: "Lead hinzufügen",
    new_booking: "Neue Buchung",
    create_new_agent: "Neuen Agenten erstellen",
    save_settings: "Einstellungen speichern",
    save_changes: "Änderungen speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    edit: "Bearbeiten",
    view: "Anzeigen",
    download: "Herunterladen",
    sync: "Synchronisieren",
    sync_agent_stream: "Agenten-Stream synchronisieren",
    record_voice_prompt: "Sprachansage aufnehmen",
    connect_google_calendar: "Google Kalender verbinden",
    google_calendar_connected: "Google Kalender verbunden",
    search_leads_placeholder: "Leads nach Name, E-Mail, Telefon oder Firma durchsuchen...",
    search_placeholder: "Apex Voice AI durchsuchen (Agenten, Anrufe, Leads)...",
    tab_all: "Alle",
    tab_new: "Neu",
    tab_qualified: "Qualifiziert",
    tab_appointment_set: "Termin vereinbart",
    tab_contacted: "Kontaktiert",
    tab_do_not_call: "Nicht anrufen",
    col_contact: "KONTAKT",
    col_phone_email: "TELEFON & E-MAIL",
    col_lead_score: "LEAD-PUNKTZAHL",
    col_status: "STATUS",
    col_campaign: "KAMPAGNE",
    col_last_call_outcome: "LETZTES ERGEBNIS",
    col_actions: "AKTIONEN",
    no_contacts_recorded: "Noch keine Kontakte oder Leads in der Datenbank gespeichert.",
    super_admin: "Super-Admin",
    mission_control: "Leitstelle (Mission Control)",
    platform_control: "Plattform-Steuerung",
    tenant_organizations: "Mandanten-Organisationen",
    team_super_admins: "Team & Super-Administratoren",
    team: "Team",
    global_calls_inspector: "Globaler Anruf-Inspektor",
    infrastructure_ai: "Infrastruktur & KI",
    telephony_sip_trunks: "Telefonie & SIP-Trunks",
    voice_ai_llm_engines: "Sprach-KI & LLM-Engines",
    email_sms_gateways: "E-Mail & SMS Gateways",
    external_servers: "Externe Server",
    plans_billing_quotas: "Tarife & Abrechnungskontingente",
    security_dnc_waf: "Sicherheit, DNC & WAF",
    audit_logs_compliance: "Audit-Protokolle & Compliance",
    global_announcements: "Globale Ankündigungen",
    analytics_revenue: "Analytik & Umsatz",
  },
  es: {
    overview: "Visión General",
    voice_operations: "Operaciones de Voz",
    live_calls: "Llamadas en Vivo",
    live_supervisor: "Supervisor en Vivo",
    voice_agents: "Agentes de Voz",
    flow_builder: "Constructor de Flujos",
    campaigns: "Campañas Salientes",
    data_context: "Datos y Contexto",
    knowledge_base: "Base de Conocimientos",
    contacts_leads: "Contactos y Leads",
    contacts_database: "Base de Datos de Contactos y Prospectos",
    contacts_subtitle: "Registro unificado de llamadas entrantes, prospectos, puntuaciones e historial de llamadas.",
    calendar_bookings: "Calendario y Citas",
    appointments: "Citas y Reservas",
    appointments_subtitle: "Administre y visualice citas programadas mediante llamadas de IA.",
    tools_integrations: "Herramientas e Integraciones",
    tools: "Herramientas",
    google_sheets: "Google Sheets",
    phone_numbers: "Números de Teléfono",
    sip_connections: "Conexiones SIP",
    smart_amd: "Smart AMD 2.0",
    intelligence_logs: "Inteligencia y Registros",
    funnels: "Embudos de Conversación",
    ab_testing: "Laboratorio A/B",
    call_history: "Historial de Llamadas",
    analytics: "Suite Analítica",
    workspace: "Espacio de Trabajo",
    templates: "Plantillas",
    credits_billing: "Créditos y Facturación",
    settings: "Configuración",
    voice_recorder: "Grabadora de Voz y Bóveda de Audio",
    voice_recorder_subtitle: "Escuche, gestione, reordene, busque y filtre grabaciones históricas de llamadas.",
    voice_credits: "Créditos de Voz",
    add_funds: "Agregar Fondos",
    my_dashboard: "Mi Panel",
    welcome_back: "Bienvenido Alex DeVries • Operaciones Empresariales Activas",
    enterprise_voice_operations: "Operaciones de Voz Empresariales",
    today: "Hoy",
    export_csv: "Exportar CSV",
    add_lead: "Agregar Prospecto",
    new_booking: "Nueva Reserva",
    create_new_agent: "Crear Nuevo Agente",
    save_settings: "Guardar Configuración",
    save_changes: "Guardar Cambios",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    view: "Ver",
    download: "Descargar",
    sync: "Sincronizar",
    sync_agent_stream: "Sincronizar Flujo de Agentes",
    record_voice_prompt: "Grabar Mensaje de Voz",
    connect_google_calendar: "Conectar Google Calendar",
    google_calendar_connected: "Google Calendar Conectado",
    search_leads_placeholder: "Buscar prospectos por nombre, correo, teléfono, empresa...",
    search_placeholder: "Buscar en Apex Voice AI (Agentes, Llamadas, Leads)...",
    tab_all: "Todos",
    tab_new: "Nuevo",
    tab_qualified: "Calificado",
    tab_appointment_set: "Cita Agendada",
    tab_contacted: "Contactado",
    tab_do_not_call: "No Llamar",
    col_contact: "CONTACTO",
    col_phone_email: "TELÉFONO Y CORREO",
    col_lead_score: "PUNTUACIÓN",
    col_status: "ESTADO",
    col_campaign: "CAMPAÑA",
    col_last_call_outcome: "RESULTADO LLAMADA",
    col_actions: "ACCIONES",
    no_contacts_recorded: "No hay contactos o prospectos registrados aún.",
    super_admin: "Superadministrador",
    mission_control: "Centro de Control",
    platform_control: "Control de Plataforma",
    tenant_organizations: "Organizaciones de Clientes",
    team_super_admins: "Equipo y Superadministradores",
    team: "Equipo",
    global_calls_inspector: "Inspector Global de Llamadas",
    infrastructure_ai: "Infraestructura e IA",
    telephony_sip_trunks: "Telefonía y Troncales SIP",
    voice_ai_llm_engines: "Motores de IA de Voz y LLM",
    email_sms_gateways: "Pasarelas de Correo y SMS",
    external_servers: "Servidores Externos",
    plans_billing_quotas: "Planes y Cuotas de Facturación",
    security_dnc_waf: "Seguridad, DNC y WAF",
    audit_logs_compliance: "Registros de Auditoría y Cumplimiento",
    global_announcements: "Anuncios Globales",
    analytics_revenue: "Analítica e Ingresos",
  },
  fr: {
    overview: "Vue d'ensemble",
    voice_operations: "Opérations Vocales",
    live_calls: "Appels en Direct",
    live_supervisor: "Superviseur en Direct",
    voice_agents: "Agents Vocaux IA",
    flow_builder: "Générateur de Flux",
    campaigns: "Campagnes d'Appels",
    data_context: "Données & Contexte",
    knowledge_base: "Base de Connaissances",
    contacts_leads: "Contacts & Prospects",
    contacts_database: "Base de Données Contacts & Prospects",
    contacts_subtitle: "Registre unifié des appelants entrants, prospects, scores et historiques d'appels.",
    calendar_bookings: "Calendrier & Rendez-vous",
    appointments: "Rendez-vous",
    appointments_subtitle: "Gérer et consulter les rendez-vous programmés via les appels IA.",
    tools_integrations: "Outils & Intégrations",
    tools: "Outils",
    google_sheets: "Google Sheets",
    phone_numbers: "Numéros de Téléphone",
    sip_connections: "Connexions SIP",
    smart_amd: "Smart AMD 2.0",
    intelligence_logs: "Intelligence & Journaux",
    funnels: "Entonnoirs de Conversation",
    ab_testing: "Lab de Tests A/B",
    call_history: "Historique des Appels",
    analytics: "Suite Analytique",
    workspace: "Espace de Travail",
    templates: "Modèles",
    credits_billing: "Crédits & Facturation",
    settings: "Paramètres",
    voice_recorder: "Enregistreur Vocal & Coffre Audio",
    voice_recorder_subtitle: "Écoutez, gérez, réorganisez, recherchez et filtrez tous les enregistrements audio.",
    voice_credits: "Crédits Vocaux",
    add_funds: "Ajouter des Fonds",
    my_dashboard: "Mon Tableau de Bord",
    welcome_back: "Bienvenue Alex DeVries • Opérations Actives",
    enterprise_voice_operations: "Opérations Vocales d'Entreprise",
    today: "Aujourd'hui",
    export_csv: "Exporter CSV",
    add_lead: "Ajouter Prospect",
    new_booking: "Nouveau Rendez-vous",
    create_new_agent: "Créer un Agent",
    save_settings: "Enregistrer les Paramètres",
    save_changes: "Enregistrer les Modifications",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    view: "Voir",
    download: "Télécharger",
    sync: "Synchroniser",
    sync_agent_stream: "Synchroniser Flux Agent",
    record_voice_prompt: "Enregistrer Message Vocal",
    connect_google_calendar: "Connecter Google Calendar",
    google_calendar_connected: "Google Calendar Connecté",
    search_leads_placeholder: "Rechercher des prospects par nom, email, téléphone...",
    search_placeholder: "Rechercher dans Apex Voice AI...",
    tab_all: "Tous",
    tab_new: "Nouveau",
    tab_qualified: "Qualifié",
    tab_appointment_set: "Rendez-vous Fixé",
    tab_contacted: "Contacté",
    tab_do_not_call: "Ne Pas Appeler",
    col_contact: "CONTACT",
    col_phone_email: "TÉLÉPHONE & EMAIL",
    col_lead_score: "SCORE PROSPECT",
    col_status: "STATUT",
    col_campaign: "CAMPAGNE",
    col_last_call_outcome: "RÉSULTAT DU DERNIER APPEL",
    col_actions: "ACTIONS",
    no_contacts_recorded: "Aucun contact ou prospect enregistré pour le moment.",
    super_admin: "Super Administrateur",
    mission_control: "Poste de Commande",
    platform_control: "Contrôle de Plateforme",
    tenant_organizations: "Organisations Clientes",
    team_super_admins: "Équipe & Super Admins",
    team: "Équipe",
    global_calls_inspector: "Inspecteur Global des Appels",
    infrastructure_ai: "Infrastructure & IA",
    telephony_sip_trunks: "Téléphonie & Trunks SIP",
    voice_ai_llm_engines: "Moteurs IA Vocale & LLM",
    email_sms_gateways: "Passerelles Email & SMS",
    external_servers: "Serveurs Externes",
    plans_billing_quotas: "Forfaits & Quotas",
    security_dnc_waf: "Sécurité, DNC & WAF",
    audit_logs_compliance: "Journaux d'Audit & Conformité",
    global_announcements: "Annonces Générales",
    analytics_revenue: "Analytique & Revenus",
  },
  ur: {
    overview: "ڈیش بورڈ جائزہ",
    voice_operations: "وائس آپریشنز",
    live_calls: "لائیو کالز",
    live_supervisor: "لائیو سپروائزر",
    voice_agents: "وائس ایجنٹس",
    flow_builder: "فلو بلڈر",
    campaigns: "مہمات",
    data_context: "ڈیٹا اور سیاق و سباق",
    knowledge_base: "علم کا ذخیرہ",
    contacts_leads: "رابطے اور لیڈز",
    contacts_database: "رابطے اور لیڈ ڈیٹا بیس",
    contacts_subtitle: "ان باؤنڈ کالرز، آؤٹ باؤنڈ پراسپیکٹس، لیڈ اسکورز اور کال ہسٹری کا مشترکہ ریکارڈ۔",
    calendar_bookings: "کیلنڈر اور بکنگز",
    appointments: "ملاقاتیں اور بکنگز",
    appointments_subtitle: "AI کالز سے طے شدہ ملاقاتوں کا انتظام اور جائزہ لیں۔",
    tools_integrations: "ٹولز اور انضمام",
    tools: "ٹولز",
    google_sheets: "گوگل شیٹس سنک",
    phone_numbers: "فون نمبرز",
    sip_connections: "SIP کنکشنز",
    smart_amd: "سمارٹ AMD 2.0",
    intelligence_logs: "انٹیلی جنس اور لاگز",
    funnels: "گفتگو کے فینلز",
    ab_testing: "A/B ٹیسٹنگ لیب",
    call_history: "کال ہسٹری",
    analytics: "تجزیاتی سویٹ",
    workspace: "ورک اسپیس",
    templates: "ٹیمپلیٹس",
    credits_billing: "کریڈٹس اور بلنگ",
    settings: "ترتیبات",
    voice_recorder: "وائس ریکارڈر اور آڈیو والٹ",
    voice_recorder_subtitle: "تمام تاریخی کال آڈیو ریکارڈنگز، وائس پرامپٹس اور ویو فارمز سنیں اور منظم کریں۔",
    voice_credits: "وائس کریڈٹس",
    add_funds: "فنڈز شامل کریں",
    my_dashboard: "میرا ڈیش بورڈ",
    welcome_back: "خوش آمدید Alex DeVries • انٹرپرائز آپریشنز فعال ہیں",
    enterprise_voice_operations: "انٹرپرائز وائس آپریشنز",
    today: "آج",
    export_csv: "CSV برآمد کریں",
    add_lead: "لیڈ شامل کریں",
    new_booking: "نئی بکنگ",
    create_new_agent: "نیا ایجنٹ بنائیں",
    save_settings: "ترتیبات محفوظ کریں",
    save_changes: "تبدیلیاں محفوظ کریں",
    cancel: "منسوخ کریں",
    delete: "حذف کریں",
    edit: "ترمیم کریں",
    view: "دیکھیں",
    download: "ڈاؤن لوڈ کریں",
    sync: "سنک کریں",
    sync_agent_stream: "ایجنٹ اسٹریم سنک کریں",
    record_voice_prompt: "وائس پرامپٹ ریکارڈ کریں",
    connect_google_calendar: "گوگل کیلنڈر لنک کریں",
    google_calendar_connected: "گوگل کیلنڈر منسلک ہے",
    search_leads_placeholder: "نام، ای میل، فون یا کمپنی کے ذریعے لیڈز تلاش کریں...",
    search_placeholder: "تلاش کریں Apex Voice AI...",
    tab_all: "تمام",
    tab_new: "نیا",
    tab_qualified: "اہل",
    tab_appointment_set: "ملاقات طے شدہ",
    tab_contacted: "رابطہ شدہ",
    tab_do_not_call: "کال نہ کریں",
    col_contact: "رابطہ",
    col_phone_email: "فون اور ای میل",
    col_lead_score: "لیڈ اسکور",
    col_status: "حیثیت",
    col_campaign: "مہم",
    col_last_call_outcome: "آخری کال نتیجہ",
    col_actions: "اعمال",
    no_contacts_recorded: "ابھی تک ڈیٹا بیس میں کوئی رابطہ یا لیڈ موجود نہیں ہے۔",
    super_admin: "سپر ایڈمن",
    mission_control: "مشین کنٹرول",
    platform_control: "پلیٹ فارم کنٹرول",
    tenant_organizations: "ٹیننٹ تنظیمیں",
    team_super_admins: "ٹیم اور سپر ایڈمنز",
    team: "ٹیم",
    global_calls_inspector: "عالمی کالز انسپکٹر",
    infrastructure_ai: "انفراسٹرکچر اور AI",
    telephony_sip_trunks: "ٹیلی فونی اور SIP ٹرنکس",
    voice_ai_llm_engines: "وائس AI اور LLM انجن",
    email_sms_gateways: "ای میل اور SMS گیٹ ویز",
    external_servers: "بیرونی سرورز",
    plans_billing_quotas: "پلانز اور بلنگ کوٹہ",
    security_dnc_waf: "سیکیورٹی، DNC اور WAF",
    audit_logs_compliance: "آڈٹ لاگز اور تعمیل",
    global_announcements: "عالمی اعلانات",
    analytics_revenue: "تجزیات اور آمدنی",
  },
  ar: {
    overview: "نظرة عامة",
    voice_operations: "عمليات الصوت",
    live_calls: "المكالمات المباشرة",
    live_supervisor: "المشرف المباشر",
    voice_agents: "وكلاء الصوت بالذكاء الاصطناعي",
    flow_builder: "منشئ المسارات",
    campaigns: "الحملات الصادرة",
    data_context: "البيانات والسياق",
    knowledge_base: "قاعدة المعرفة",
    contacts_leads: "جهات الاتصال والعملاء",
    contacts_database: "قاعدة بيانات جهات الاتصال والعملاء",
    contacts_subtitle: "سجل موحد للمتصلين الواردين والعملاء المحتملين وسجلات المكالمات.",
    calendar_bookings: "التقويم والحجوزات",
    appointments: "المواعيد",
    appointments_subtitle: "إدارة المواعيد المجدولة من مكالمات الذكاء الاصطناعي.",
    tools_integrations: "الأدوات والتكاملات",
    tools: "الأدوات",
    google_sheets: "جداول بيانات جوجل",
    phone_numbers: "أرقام الهواتف",
    sip_connections: "اتصالات SIP",
    smart_amd: "Smart AMD 2.0",
    intelligence_logs: "السجلات والتحليلات",
    funnels: "مسارات المحادثة",
    ab_testing: "مختبر اختبار A/B",
    call_history: "سجل المكالمات",
    analytics: "مجموعة التحليلات",
    workspace: "مساحة العمل",
    templates: "القوالب",
    credits_billing: "الرصيد والفوترة",
    settings: "الإعدادات",
    voice_recorder: "مسجل الصوت وخزينة الصوتيات",
    voice_recorder_subtitle: "الاستماع وإدارة وترتيب وفلترة جميع تسجيلات المكالمات التاريخية.",
    voice_credits: "رصيد الصوت",
    add_funds: "إضافة رصيد",
    my_dashboard: "لوحتي",
    welcome_back: "مرحبًا Alex DeVries • العمليات نشطة",
    enterprise_voice_operations: "عمليات الصوت للمؤسسات",
    today: "اليوم",
    export_csv: "تصدير CSV",
    add_lead: "إضافة عميل محتمل",
    new_booking: "حجز جديد",
    create_new_agent: "إنشاء وكيل جديد",
    save_settings: "حفظ الإعدادات",
    save_changes: "حفظ التغييرات",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    view: "عرض",
    download: "تنزيل",
    sync: "مزامنة",
    sync_agent_stream: "مزامنة تسجيلات الوكلاء",
    record_voice_prompt: "تسجيل صوتي",
    connect_google_calendar: "ربط تقويم جوجل",
    google_calendar_connected: "تقويم جوجل متصل",
    search_leads_placeholder: "البحث عن العملاء بالاسم، البريد، الهاتف...",
    search_placeholder: "البحث في Apex Voice AI...",
    tab_all: "الكل",
    tab_new: "جديد",
    tab_qualified: "مؤهل",
    tab_appointment_set: "تم تحديد موعد",
    tab_contacted: "تم التواصل",
    tab_do_not_call: "عدم الاتصال",
    col_contact: "جهة الاتصال",
    col_phone_email: "الهاتف والبريد",
    col_lead_score: "درجة العميل",
    col_status: "الحالة",
    col_campaign: "الحملة",
    col_last_call_outcome: "نتيجة آخر مكالمة",
    col_actions: "الإجراءات",
    no_contacts_recorded: "لا توجد جهات اتصال مسجلة حتى الآن.",
    super_admin: "المشرف العام",
    mission_control: "مركز القيادة",
    platform_control: "إدارة المنصة",
    tenant_organizations: "المؤسسات المشتركة",
    team_super_admins: "فريق المشرفين",
    team: "الفريق",
    global_calls_inspector: "مفتش المكالمات العالمي",
    infrastructure_ai: "البنية التحتية والذكاء الاصطناعي",
    telephony_sip_trunks: "خطوط SIP والاتصالات",
    voice_ai_llm_engines: "محركات الصوت والذكاء الاصطناعي",
    email_sms_gateways: "بوابات البريد والرسائل",
    external_servers: "الخوادم الخارجية",
    plans_billing_quotas: "الخطط والفوترة",
    security_dnc_waf: "الأمان وجدار الحماية",
    audit_logs_compliance: "سجلات التدقيق والامتثال",
    global_announcements: "الإعلانات العامة",
    analytics_revenue: "التحليلات والإيرادات",
  },
  zh: {
    overview: "总览",
    voice_operations: "语音运营",
    live_calls: "实时通话",
    live_supervisor: "实时监控",
    voice_agents: "AI 语音智能体",
    flow_builder: "可视化流程构建器",
    campaigns: "呼出营销活动",
    data_context: "数据与上下文",
    knowledge_base: "知识库",
    contacts_leads: "联系人与线索",
    contacts_database: "联系人与线索数据库",
    contacts_subtitle: "呼入者、呼出潜在客户、线索评分和通话历史的统一账本。",
    calendar_bookings: "日历与预约",
    appointments: "预约与排程",
    appointments_subtitle: "管理并查看由 AI 通话排定的所有预约日程。",
    tools_integrations: "工具与集成",
    tools: "工具",
    google_sheets: "Google 表格同步",
    phone_numbers: "电话号码",
    sip_connections: "SIP 中继连接",
    smart_amd: "Smart AMD 2.0 答录机检测",
    intelligence_logs: "情报与日志",
    funnels: "对话漏斗",
    ab_testing: "A/B 测试实验室",
    call_history: "通话历史记录",
    analytics: "分析套件",
    workspace: "工作区",
    templates: "智能体模板",
    credits_billing: "额度与账单",
    settings: "工作区设置",
    voice_recorder: "录音管理器与音频库",
    voice_recorder_subtitle: "收听、管理、重新排序、搜索和筛选所有历史通话录音与提示音。",
    voice_credits: "语音额度",
    add_funds: "充值额度",
    my_dashboard: "我的控制台",
    welcome_back: "欢迎回来 Alex DeVries • 企业运营活跃中",
    enterprise_voice_operations: "企业级语音运营中心",
    today: "今日",
    export_csv: "导出 CSV",
    add_lead: "添加线索",
    new_booking: "新建预约",
    create_new_agent: "创建新智能体",
    save_settings: "保存设置",
    save_changes: "保存更改",
    cancel: "取消",
    delete: "删除",
    edit: "编辑",
    view: "查看",
    download: "下载",
    sync: "同步",
    sync_agent_stream: "同步智能体录音流",
    record_voice_prompt: "录制语音提示",
    connect_google_calendar: "关联 Google 日历",
    google_calendar_connected: "Google 日历已关联",
    search_leads_placeholder: "按姓名、邮箱、电话、公司搜索线索...",
    search_placeholder: "搜索 Apex Voice AI...",
    tab_all: "全部",
    tab_new: "新线索",
    tab_qualified: "已合格",
    tab_appointment_set: "已排定预约",
    tab_contacted: "已联系",
    tab_do_not_call: "勿扰名单",
    col_contact: "联系人",
    col_phone_email: "电话与邮箱",
    col_lead_score: "线索评分",
    col_status: "状态",
    col_campaign: "营销活动",
    col_last_call_outcome: "最后通话结果",
    col_actions: "操作",
    no_contacts_recorded: "数据库中暂无联系人记录。",
    super_admin: "超级管理员",
    mission_control: "指挥中心",
    platform_control: "平台控制",
    tenant_organizations: "租户组织",
    team_super_admins: "团队与超级管理员",
    team: "团队",
    global_calls_inspector: "全局通话监控",
    infrastructure_ai: "基础设施与 AI",
    telephony_sip_trunks: "电话线路与 SIP 中继",
    voice_ai_llm_engines: "语音 AI 与 LLM 引擎",
    email_sms_gateways: "邮件与短信网关",
    external_servers: "外部服务器",
    plans_billing_quotas: "套餐与账单配额",
    security_dnc_waf: "安全、DNC 与防火墙",
    audit_logs_compliance: "审计日志与合规",
    global_announcements: "全局公告",
    analytics_revenue: "分析与营收",
  },
  ja: {
    overview: "概要",
    voice_operations: "音声運用",
    live_calls: "ライブ通話",
    live_supervisor: "ライブ監視",
    voice_agents: "AI音声エージェント",
    flow_builder: "フロービルダー",
    campaigns: "発信キャンペーン",
    data_context: "データとコンテキスト",
    knowledge_base: "ナレッジベース",
    contacts_leads: "連絡先とリード",
    contacts_database: "連絡先・リードデータベース",
    contacts_subtitle: "着信発信の全記録、リードスコア、通話履歴を一元管理。",
    calendar_bookings: "カレンダーと予約",
    appointments: "予約一覧",
    appointments_subtitle: "AI通話から自動スケジュールされた予約を管理・確認。",
    tools_integrations: "ツールと連携",
    tools: "ツール",
    google_sheets: "Google スプレッドシート連携",
    phone_numbers: "電話番号",
    sip_connections: "SIP接続",
    smart_amd: "Smart AMD 2.0 留守電検知",
    intelligence_logs: "インテリジェンスとログ",
    funnels: "会話ファネル",
    ab_testing: "A/Bテストラボ",
    call_history: "通話履歴",
    analytics: "分析スイート",
    workspace: "ワークスペース",
    templates: "テンプレート",
    credits_billing: "クレジットと請求",
    settings: "設定",
    voice_recorder: "ボイスレコーダー・音声保管庫",
    voice_recorder_subtitle: "過去の通話録音、音声プロンプト、波形を再生・管理・検索。",
    voice_credits: "音声クレジット",
    add_funds: "クレジットチャージ",
    my_dashboard: "マイダッシュボード",
    welcome_back: "おかえりなさい Alex DeVries • エンタープライズ運用中",
    enterprise_voice_operations: "エンタープライズ音声運用",
    today: "今日",
    export_csv: "CSVエクスポート",
    add_lead: "リード追加",
    new_booking: "新規予約",
    create_new_agent: "新規エージェント作成",
    save_settings: "設定を保存",
    save_changes: "変更を保存",
    cancel: "キャンセル",
    delete: "削除",
    edit: "編集",
    view: "表示",
    download: "ダウンロード",
    sync: "同期",
    sync_agent_stream: "エージェント録音を同期",
    record_voice_prompt: "音声を録音",
    connect_google_calendar: "Google カレンダー連携",
    google_calendar_connected: "Google カレンダー連携済",
    search_leads_placeholder: "名前、メール、電話番号、会社名で検索...",
    search_placeholder: "Apex Voice AI を検索...",
    tab_all: "すべて",
    tab_new: "新規",
    tab_qualified: "適格",
    tab_appointment_set: "予約完了",
    tab_contacted: "連絡済",
    tab_do_not_call: "架電禁止",
    col_contact: "連絡先",
    col_phone_email: "電話・メール",
    col_lead_score: "リードスコア",
    col_status: "ステータス",
    col_campaign: "キャンペーン",
    col_last_call_outcome: "最終通話結果",
    col_actions: "操作",
    no_contacts_recorded: "データベースに連絡先が登録されていません。",
    super_admin: "特権管理者",
    mission_control: "管制センター",
    platform_control: "プラットフォーム制御",
    tenant_organizations: "テナント組織",
    team_super_admins: "チーム・特権管理者",
    team: "チーム",
    global_calls_inspector: "グローバル通話監視",
    infrastructure_ai: "インフラ・AIエンジン",
    telephony_sip_trunks: "電話回線・SIPトランク",
    voice_ai_llm_engines: "音声AI・LLMエンジン",
    email_sms_gateways: "メール・SMSゲートウェイ",
    external_servers: "外部サーバー",
    plans_billing_quotas: "プラン・請求枠",
    security_dnc_waf: "セキュリティ・WAF",
    audit_logs_compliance: "監査ログ・コンプライアンス",
    global_announcements: "グローバル通知",
    analytics_revenue: "分析・収益",
  },
};

// Normalized English String to Translation Key Map
export const STRING_KEY_MAP: Record<string, string> = {
  // Page Titles
  "overview": "overview",
  "dashboard": "my_dashboard",
  "my dashboard": "my_dashboard",
  "contacts & leads": "contacts_leads",
  "contacts & lead database": "contacts_database",
  "contacts": "contacts_leads",
  "leads": "contacts_leads",
  "calendar & bookings": "calendar_bookings",
  "calendar & appointments": "calendar_bookings",
  "calendar": "calendar_bookings",
  "appointments": "appointments",
  "voice agents": "voice_agents",
  "ai voice agents": "voice_agents",
  "voice operations": "voice_operations",
  "live calls": "live_calls",
  "live supervisor": "live_supervisor",
  "flow builder": "flow_builder",
  "visual flow builder": "flow_builder",
  "campaigns": "campaigns",
  "outbound campaigns": "campaigns",
  "knowledge base": "knowledge_base",
  "tools & integrations": "tools_integrations",
  "tools": "tools",
  "google sheets": "google_sheets",
  "phone numbers": "phone_numbers",
  "sip connections": "sip_connections",
  "smart amd 2.0": "smart_amd",
  "smart amd": "smart_amd",
  "conversation funnels": "funnels",
  "funnels": "funnels",
  "a/b testing lab": "ab_testing",
  "a/b testing": "ab_testing",
  "call history": "call_history",
  "analytics suite": "analytics",
  "analytics": "analytics",
  "templates": "templates",
  "agent templates": "templates",
  "credits & billing": "credits_billing",
  "credits": "credits_billing",
  "workspace settings": "settings",
  "settings": "settings",
  "voice recorder": "voice_recorder",
  "voice recorder & audio vault": "voice_recorder",
  "voice recordings": "voice_recorder",
  "recordings": "voice_recorder",
  
  // Super Admin Titles
  "super admin": "super_admin",
  "super admin console": "super_admin",
  "mission control": "mission_control",
  "platform control": "platform_control",
  "tenant organizations": "tenant_organizations",
  "team & super admins": "team_super_admins",
  "team": "team",
  "global calls inspector": "global_calls_inspector",
  "infrastructure & ai": "infrastructure_ai",
  "telephony & sip trunks": "telephony_sip_trunks",
  "voice ai & llm engines": "voice_ai_llm_engines",
  "email & sms gateways": "email_sms_gateways",
  "external servers": "external_servers",
  "plans & billing quotas": "plans_billing_quotas",
  "security, dnc & waf": "security_dnc_waf",
  "audit logs & compliance": "audit_logs_compliance",
  "global announcements": "global_announcements",
  "analytics & revenue": "analytics_revenue",

  // Common UI Buttons & Actions
  "export csv": "export_csv",
  "add lead": "add_lead",
  "+ add lead": "add_lead",
  "new booking": "new_booking",
  "+ new booking": "new_booking",
  "create new agent": "create_new_agent",
  "+ create new agent": "create_new_agent",
  "save settings": "save_settings",
  "save changes": "save_changes",
  "cancel": "cancel",
  "delete": "delete",
  "edit": "edit",
  "view": "view",
  "download": "download",
  "sync": "sync",
  "sync agent stream": "sync_agent_stream",
  "record voice prompt": "record_voice_prompt",
  "connect google calendar": "connect_google_calendar",
  "google calendar connected": "google_calendar_connected",
  "browse templates": "browse_templates",
  "add funds": "add_funds",
  "voice credits": "voice_credits",
  "today": "today",

  // Subtitles & Sentences
  "unified ledger of inbound callers, outbound prospects, lead scores, and call histories.": "contacts_subtitle",
  "manage and view scheduled appointments from ai calls": "appointments_subtitle",
  "listen, manage, reorder, search, and filter all historical call audio recordings, voice prompts, and ai waveforms.": "voice_recorder_subtitle",
  "no contacts or leads recorded in database yet.": "no_contacts_recorded",
  "search leads by name, email, phone, company...": "search_leads_placeholder",

  // Table Columns
  "contact": "col_contact",
  "phone & email": "col_phone_email",
  "lead score": "col_lead_score",
  "status": "col_status",
  "campaign": "col_campaign",
  "last call outcome": "col_last_call_outcome",
  "actions": "col_actions",

  // Tabs & Filters
  "all": "tab_all",
  "new": "tab_new",
  "qualified": "tab_qualified",
  "appointment set": "tab_appointment_set",
  "contacted": "tab_contacted",
  "do not call": "tab_do_not_call",
};

export function translate(keyOrText: string, lang: string = "en"): string {
  if (!keyOrText) return "";
  if (lang === "en") {
    // Return original key or English translation if available
    if (TRANSLATIONS["en"] && TRANSLATIONS["en"][keyOrText]) {
      return TRANSLATIONS["en"][keyOrText];
    }
    return keyOrText;
  }

  // 1. Direct translation key match in target language
  if (TRANSLATIONS[lang] && TRANSLATIONS[lang][keyOrText]) {
    return TRANSLATIONS[lang][keyOrText];
  }

  // 2. Normalized string lookup via STRING_KEY_MAP
  const normalized = keyOrText.toLowerCase().trim().replace(/^[+•-]\s*/, "");
  const mappedKey = STRING_KEY_MAP[normalized] || STRING_KEY_MAP[keyOrText.toLowerCase().trim()];
  if (mappedKey) {
    if (TRANSLATIONS[lang] && TRANSLATIONS[lang][mappedKey]) {
      const isPlus = keyOrText.trim().startsWith("+");
      return isPlus ? `+ ${TRANSLATIONS[lang][mappedKey]}` : TRANSLATIONS[lang][mappedKey];
    }
    // Fallback translation in German, Spanish, French, etc.
    if (TRANSLATIONS["de"] && TRANSLATIONS["de"][mappedKey] && lang === "de") {
      return TRANSLATIONS["de"][mappedKey];
    }
    if (TRANSLATIONS["es"] && TRANSLATIONS["es"][mappedKey] && lang === "es") {
      return TRANSLATIONS["es"][mappedKey];
    }
  }

  // 3. Substring / Word-level fallback matching for composite labels
  if (normalized.includes("contact") && normalized.includes("lead")) {
    if (TRANSLATIONS[lang]?.contacts_database) return TRANSLATIONS[lang].contacts_database;
  }
  if (normalized.includes("export") && normalized.includes("csv")) {
    if (TRANSLATIONS[lang]?.export_csv) return TRANSLATIONS[lang].export_csv;
  }
  if (normalized.includes("add") && normalized.includes("lead")) {
    if (TRANSLATIONS[lang]?.add_lead) return `+ ${TRANSLATIONS[lang].add_lead}`;
  }

  // 4. Default return original text if no translation rule exists
  return keyOrText;
}
